version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
# run linting tool
# docker-compose run --rm app sh -c "flake8"

# run cli of django to create a project
# docker-compose run --rm app sh -c "django-admin startproject app ."
